apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-initial
spec:
  selector:
    matchLabels:
      app: caps
      ver: initial
  replicas: 3
  template:
    metadata:
      labels:
        app: caps    
        ver: initial
    spec:
      containers:
      - name: caps
        image: rcdotnet/cameleon:initial
        ports:
        - containerPort: 80
      
      
       