#!/usr/bin/env bash

# This script deploys the infrastructure on AWS us-west-2 with Cloud formation and deploys the application initial state on 
# the provisioned Cluster. The CloudFormation script are generated by EKSCTL

echo "Creating EKS cluster."
./create.sh cluster CloudFormation/Cluster.json CloudFormation/empty.json

# waiting the stack complete
echo "Waiting the stack bilding stack to finish"
aws cloudformation wait stack-create-complete --stack-name cluster

echo "Creating NodeGroup"
./create.sh NodeGroup CloudFormation/NodeGroup.json CloudFormation/empty.json

# waiting the stack complete
echo "Waiting the NodeGroup building stack to finish"
aws cloudformation wait stack-create-complete --stack-name NodeGroup

# Configuring kubectl
echo "configuring kubectl to working with the new cluster"
eksctl utils write-kubeconfig capstone-cluster

# Deploying the application the first time
echo "Deploying the application"
make deploy_kubernetes

# Waiting until the deployment is ready
echo "waiting the apication coming to live"
kubectl rollout status deployment/capstone-initial

#show info of the public endpoint
echo "Please find the public endpont bellow, use port 8090!"
echo "After the initial Apache page confirmed the app is available at URL:8090/admin.php"
kubectl get svc
